#ifndef _METAL_CPP_FRAMEWORK_RENDER_HPP
#define _METAL_CPP_FRAMEWORK_RENDER_HPP

#pragma once

#include <RENDER_FRAMEWORK_API.h>

#define NS_PRIVATE_IMPLEMENTATION
#define CA_PRIVATE_IMPLEMENTATION
#define MTL_PRIVATE_IMPLEMENTATION
// #include "Metal.hpp"

RENDER_FRAMEWORK_API void RenderFunction();

#endif /* _METAL_CPP_FRAMEWORK_RENDER_HPP */
