#ifndef _METAL_CPP_FRAMEWORK_RENDER_HPP
#define _METAL_CPP_FRAMEWORK_RENDER_HPP

#pragma once

#include <RENDER_FRAMEWORK_API.h>


RENDER_FRAMEWORK_API void RenderFunction();

#endif /* _METAL_CPP_FRAMEWORK_RENDER_HPP */
